# action.yml

name: minio-download
description: "Action that lets you download objects from a MinIO server"
inputs:
  url:
    description: "URL of the MinIO server"
    required: true
  access-key:
    description: "Access Key for the MinIO server"
    required: true
  secret-key:
    description: "Secret Key for the MinIO server"
    required: true
  local-path:
    description: 'Path of the local object'
    required: true
    default: './'
  remote-path:
    description: 'Path to remote object'
    required: true

runs:
  using: composite
  steps:
    - name: Setup mc
      working-directory: /usr/local/bin
      run: |
        [ -n "$(which mc)" ] && exit 0
        arch=$(dpkg --print-architecture | sed 's/armhf/arm/g')
        sudo wget --progres=dot:binary \
          "https://dl.min.io/client/mc/release/linux-${arch}/mc"
        sudo chmod +x mc
      shell: bash

    - name: Setup s3 alias
      run: |
        mc alias set s3 "${{ inputs.url }}" \
          "${{ inputs.access-key }}" "${{ inputs.secret-key }}"
      shell: bash

    - name: Download objects
      run: |
        echo "Will download ${{ inputs.remote-path }} to ${{ inputs.local-path }}"
        remote_path=${{ inputs.remote-path }}
        if [ "${remote_path#*'*'}" != "$remote_path" ]; then
          # Handle remote_files with wildcards 
          remote_dir=$(dirname "$remote_path")
          remote_files=$(basename "$remote_path")
          IFS=$'\n'
          for p in $(mc find "s3/$remote_dir" \
            --maxdepth 2 --name "$remote_files" | sort -u); do
              mc cp -r "$p" "${{ inputs.local-path }}";
          done
          unset IFS
        else
          mc cp -r "s3/$remote_path" "${{ inputs.local-path }}"
        fi
      shell: bash
