# action.yml

name: minio-download
description: "Action that lets you download objects from a MinIO server"
inputs:
  url:
    description: "URL of the MinIO server"
    required: true
  access-key:
    description: "Access Key for the MinIO server"
    required: true
  secret-key:
    description: "Secret Key for the MinIO server"
    required: true
  local-path:
    description: 'Path of the local object'
    required: true
    default: './'
  remote-path:
    description: 'Path to remote object'
    required: true

runs:
  using: composite
  steps:
    - name: Check if mc is installed
      id: check-mc
      run: |
        if [[ -n "$(which mc)" ]]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Download latest mc SHA256
      id: mc-sha
      if: steps.check-mc.outputs.exists == 'false'
      run: |
        arch=$(dpkg --print-architecture | sed 's/armhf/arm/g')
        sha=$(wget -qO- \
          "https://dl.min.io/client/mc/release/linux-${arch}/mc.sha256sum" \
          | awk '{print $1}')
        echo "sha256=$sha" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Cache mc binary
      id: cache-mc
      if: steps.check-mc.outputs.exists == 'false'
      uses: actions/cache@v5
      with:
        path: /usr/local/bin/mc
        key: "mc-${{ steps.mc-sha.outputs.sha256 }}"

    - name: Setup mc
      working-directory: /usr/local/bin
      if: >-
        steps.check-mc.outputs.exists == 'false' &&
        steps.cache-mc.outputs.cache-hit != 'true'
      run: |
        arch=$(dpkg --print-architecture | sed 's/armhf/arm/g')
        sudo wget --progres=dot:binary \
          "https://dl.min.io/client/mc/release/linux-${arch}/mc"
        sudo chmod +x mc
      shell: bash

    - name: Setup s3 alias
      env:
        URL: ${{ inputs.url }}
        ACCESS_KEY: ${{ inputs.access-key }}
        SECRET_KEY: ${{ inputs.secret-key }}
      run: mc alias set s3 "$URL" "$ACCESS_KEY" "$SECRET_KEY"
      shell: bash

    - name: Download objects
      env:
        REMOTE_PATH: ${{ inputs.remote-path }}
        LOCAL_PATH: ${{ inputs.local-path }}
      run: |
        echo "Will download ${REMOTE_PATH} to ${LOCAL_PATH}"
        if [[ "$REMOTE_PATH" =~ '*' ]]; then
          # Handle remote paths with wildcards 
          base_path="${REMOTE_PATH%%[*?\[]*}"
          base_path="${base_path%/*}"
          wildcard_path="${REMOTE_PATH#"${base_path}/"}"

          base_path="${base_path%/}"
          wildcard_path="${wildcard_path%/}"

          IFS=$'\n'
          for path in $(mc find "s3/${base_path}" --path "$wildcard_path" |
            sort -u); do
            mc cp -r "${path%/}" "${LOCAL_PATH}"
          done
          unset IFS
        else
          mc cp -r "s3/${REMOTE_PATH}" "${LOCAL_PATH}"
        fi
      shell: bash
