name: Test action

on: push

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test single file download
        uses: ./
        with:
          url: https://s3.nubificus.com
          access-key: ${{ secrets.AWS_ACCESS_KEY }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          local-path: "./"
          remote-path: "nbfc-assets/github/minio/test1.txt"

      - name: Verify files exist
        run: |
          if [[ -z $(find -name 'test*.txt') ]]; then
            echo "::error::No files were downloaded"
            exit 1
          fi
          rm -f test*.txt
        shell: bash

      - name: Test wildcard with extension download
        uses: ./
        with:
          url: https://s3.nubificus.com
          access-key: ${{ secrets.AWS_ACCESS_KEY }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          local-path: "./"
          remote-path: "nbfc-assets/github/minio/*.txt"

      - name: Verify files exist
        run: |
          if [[ -z $(find -name 'test*.txt') ]]; then
            echo "::error::No files were downloaded"
            exit 1
          fi
          rm -f test*.txt
        shell: bash

      - name: Test wildcard download
        uses: ./
        with:
          url: https://s3.nubificus.com
          access-key: ${{ secrets.AWS_ACCESS_KEY }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          local-path: "./"
          remote-path: "nbfc-assets/github/minio*/*"

      - name: Verify files exist
        run: |
          if [[ -z $(find -name 'test*.txt') ]]; then
            echo "::error::No files were downloaded"
            exit 1
          fi
          rm -f test*.txt
        shell: bash
